# Generated by Django 5.0.6 on 2026-06-18 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color',
            field=models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator('^#(?:[0-9a-fA-F]{6})$', 'Enter a valid hex color, e.g. #4f46e5.')]),
        ),
    ]
