# Generated by Django 5.0.6 on 2026-06-19 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_backfill_project_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('link_type', models.CharField(choices=[('figma', 'Figma'), ('linear', 'Linear'), ('github', 'GitHub'), ('notion', 'Notion'), ('slack', 'Slack'), ('doc', 'Document'), ('other', 'Other')], default='other', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='projects.project')),
            ],
            options={
                'ordering': ['link_type', 'label'],
            },
        ),
    ]
