# Generated by Django 5.0.6 on 2026-06-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlink',
            name='link_type',
            field=models.CharField(default='other', max_length=32),
        ),
    ]
