# Generated by Django 5.0.6 on 2026-06-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='render_mode',
            field=models.CharField(choices=[('sanitized', 'Sanitized (no scripts)'), ('interactive', 'Interactive (isolated sandbox)')], default='sanitized', max_length=12),
        ),
    ]
